-- =============================================================================
-- Sprint 0 Migration — WealthOps AI / Precept Legacy
-- Generated: 2026-03-25
-- Run against: supabase_db_atomic-crm-demo (local Supabase instance)
-- Author: Forge (Builder Agent)
-- Review: Shield (QA Agent)
-- =============================================================================

-- -----------------------------------------------------------------------------
-- 1. institutional_firms — must exist before contacts FK is added
-- -----------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS public.institutional_firms (
    id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    firm_name       text NOT NULL,
    firm_type       text,   -- 'family_office', 'ria', 'endowment', 'foundation'
    aum_estimated   text,
    aum_source      text,   -- 'adv_filing', 'manual_estimate', 'public'
    adv_crd_number  text,
    adv_last_reviewed date,
    alternatives_allocation boolean,
    silver_lake_direct      boolean,
    city            text,
    state           text,
    website         text,
    source          text,   -- 'edgar', 'directory', 'referral'
    created_at      timestamptz DEFAULT now(),
    updated_at      timestamptz DEFAULT now()
);

ALTER TABLE public.institutional_firms ENABLE ROW LEVEL SECURITY;

CREATE POLICY "anon_select_institutional_firms" ON public.institutional_firms
    FOR SELECT TO anon USING (true);

CREATE POLICY "anon_insert_institutional_firms" ON public.institutional_firms
    FOR INSERT TO anon WITH CHECK (true);


-- -----------------------------------------------------------------------------
-- 2. contacts — add new columns
-- -----------------------------------------------------------------------------

ALTER TABLE public.contacts
    ADD COLUMN IF NOT EXISTS playbook                text,
    ADD COLUMN IF NOT EXISTS institutional_firm_id   bigint REFERENCES public.institutional_firms(id),
    ADD COLUMN IF NOT EXISTS email_invalid           boolean DEFAULT false,
    ADD COLUMN IF NOT EXISTS linkedin_connected      boolean DEFAULT false,
    ADD COLUMN IF NOT EXISTS linkedin_connected_date timestamptz,
    -- linkedin_url already exists as linkedin_url — confirm in schema above: YES (column name is linkedin_url)
    ADD COLUMN IF NOT EXISTS current_sequence        text,
    ADD COLUMN IF NOT EXISTS sequence_enrolled_at    timestamptz,
    ADD COLUMN IF NOT EXISTS sequence_completed_at   timestamptz,
    ADD COLUMN IF NOT EXISTS nurture_reason          text,
    ADD COLUMN IF NOT EXISTS dd_checklist            jsonb,
    ADD COLUMN IF NOT EXISTS retail_comm_counted     boolean DEFAULT false,
    ADD COLUMN IF NOT EXISTS retail_comm_date        timestamptz;

-- New indexes on contacts
CREATE INDEX IF NOT EXISTS idx_contacts_playbook           ON public.contacts(playbook);
CREATE INDEX IF NOT EXISTS idx_contacts_current_sequence   ON public.contacts(current_sequence);
CREATE INDEX IF NOT EXISTS idx_contacts_email_invalid      ON public.contacts(email_invalid);
CREATE INDEX IF NOT EXISTS idx_contacts_linkedin_connected ON public.contacts(linkedin_connected);


-- -----------------------------------------------------------------------------
-- 3. sequences — template definitions (must exist before sequence_enrollments FK)
-- -----------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS public.sequences (
    id          text PRIMARY KEY,   -- e.g., 'A1', 'A2', 'B1'
    name        text NOT NULL,
    playbook    text NOT NULL,      -- 'A' or 'B'
    description text,
    total_steps integer,
    max_days    integer,
    steps       jsonb,              -- array of step definitions
    active      boolean DEFAULT true,
    created_at  timestamptz DEFAULT now(),
    updated_at  timestamptz DEFAULT now()
);

ALTER TABLE public.sequences ENABLE ROW LEVEL SECURITY;

CREATE POLICY "anon_select_sequences" ON public.sequences
    FOR SELECT TO anon USING (true);

CREATE POLICY "anon_insert_sequences" ON public.sequences
    FOR INSERT TO anon WITH CHECK (true);


-- -----------------------------------------------------------------------------
-- 4. email_drafts
-- -----------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS public.email_drafts (
    id                  bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    contact_id          bigint REFERENCES public.contacts(id),
    sequence_id         text,
    sequence_step       integer,
    subject             text NOT NULL,
    body                text NOT NULL,
    from_address        text,
    to_address          text,
    status              text DEFAULT 'draft',   -- 'draft','approved','sent','rejected','edited'
    created_at          timestamptz DEFAULT now(),
    reviewed_at         timestamptz,
    sent_at             timestamptz,
    marshall_notes      text,
    retail_comm_flag    boolean DEFAULT false,
    compliance_cleared  boolean DEFAULT false
);

CREATE INDEX IF NOT EXISTS idx_email_drafts_contact_id  ON public.email_drafts(contact_id);
CREATE INDEX IF NOT EXISTS idx_email_drafts_status      ON public.email_drafts(status);
CREATE INDEX IF NOT EXISTS idx_email_drafts_sequence_id ON public.email_drafts(sequence_id);
CREATE INDEX IF NOT EXISTS idx_email_drafts_created_at  ON public.email_drafts(created_at);

ALTER TABLE public.email_drafts ENABLE ROW LEVEL SECURITY;

CREATE POLICY "anon_select_email_drafts" ON public.email_drafts
    FOR SELECT TO anon USING (true);

CREATE POLICY "anon_insert_email_drafts" ON public.email_drafts
    FOR INSERT TO anon WITH CHECK (true);

CREATE POLICY "anon_update_email_drafts" ON public.email_drafts
    FOR UPDATE TO anon USING (true) WITH CHECK (true);


-- -----------------------------------------------------------------------------
-- 5. linkedin_drafts
-- -----------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS public.linkedin_drafts (
    id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    contact_id      bigint REFERENCES public.contacts(id),
    sequence_id     text,
    sequence_step   integer,
    draft_type      text,       -- 'connection_request','direct_message','content_engagement'
    message_body    text NOT NULL,
    character_count integer,
    status          text DEFAULT 'draft',  -- 'draft','approved','sent','rejected'
    created_at      timestamptz DEFAULT now(),
    sent_at         timestamptz,
    linkedin_url    text
);

CREATE INDEX IF NOT EXISTS idx_linkedin_drafts_contact_id ON public.linkedin_drafts(contact_id);
CREATE INDEX IF NOT EXISTS idx_linkedin_drafts_status     ON public.linkedin_drafts(status);
CREATE INDEX IF NOT EXISTS idx_linkedin_drafts_draft_type ON public.linkedin_drafts(draft_type);

ALTER TABLE public.linkedin_drafts ENABLE ROW LEVEL SECURITY;

CREATE POLICY "anon_select_linkedin_drafts" ON public.linkedin_drafts
    FOR SELECT TO anon USING (true);

CREATE POLICY "anon_insert_linkedin_drafts" ON public.linkedin_drafts
    FOR INSERT TO anon WITH CHECK (true);


-- -----------------------------------------------------------------------------
-- 6. call_briefs (no call_log_id FK yet — circular dep, added after call_logs)
-- -----------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS public.call_briefs (
    id                  bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    contact_id          bigint REFERENCES public.contacts(id),
    sequence_id         text,
    sequence_step       integer,
    call_priority       text DEFAULT 'normal',  -- 'hot','normal','low'
    scheduled_for       timestamptz,
    prospect_summary    text,
    trigger_summary     text,
    opener              text,
    talking_points      jsonb,
    objection_handlers  jsonb,
    voicemail_script    text,
    proposed_next_step  text,
    status              text DEFAULT 'pending', -- 'pending','completed','skipped'
    created_at          timestamptz DEFAULT now(),
    call_log_id         bigint  -- FK to call_logs.id added after call_logs is created
);

CREATE INDEX IF NOT EXISTS idx_call_briefs_contact_id    ON public.call_briefs(contact_id);
CREATE INDEX IF NOT EXISTS idx_call_briefs_status        ON public.call_briefs(status);
CREATE INDEX IF NOT EXISTS idx_call_briefs_scheduled_for ON public.call_briefs(scheduled_for);
CREATE INDEX IF NOT EXISTS idx_call_briefs_call_priority ON public.call_briefs(call_priority);

ALTER TABLE public.call_briefs ENABLE ROW LEVEL SECURITY;

CREATE POLICY "anon_select_call_briefs" ON public.call_briefs
    FOR SELECT TO anon USING (true);

CREATE POLICY "anon_insert_call_briefs" ON public.call_briefs
    FOR INSERT TO anon WITH CHECK (true);


-- -----------------------------------------------------------------------------
-- 7. call_logs
-- -----------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS public.call_logs (
    id                      bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    contact_id              bigint REFERENCES public.contacts(id),
    call_brief_id           bigint REFERENCES public.call_briefs(id),
    sequence_id             text,
    sequence_step           integer,
    called_at               timestamptz NOT NULL DEFAULT now(),
    duration_seconds        integer,
    outcome                 text,  -- 'connected_positive','connected_not_interested','voicemail','no_answer','callback_requested','wrong_number'
    notes                   text,
    callback_scheduled_for  timestamptz,
    next_action_triggered   text,
    logged_by               text DEFAULT 'marshall',
    created_at              timestamptz DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_call_logs_contact_id ON public.call_logs(contact_id);
CREATE INDEX IF NOT EXISTS idx_call_logs_outcome    ON public.call_logs(outcome);
CREATE INDEX IF NOT EXISTS idx_call_logs_called_at  ON public.call_logs(called_at);

ALTER TABLE public.call_logs ENABLE ROW LEVEL SECURITY;

CREATE POLICY "anon_select_call_logs" ON public.call_logs
    FOR SELECT TO anon USING (true);

CREATE POLICY "anon_insert_call_logs" ON public.call_logs
    FOR INSERT TO anon WITH CHECK (true);

CREATE POLICY "anon_update_call_logs" ON public.call_logs
    FOR UPDATE TO anon USING (true) WITH CHECK (true);


-- -----------------------------------------------------------------------------
-- 7b. Add deferred FK: call_briefs.call_log_id → call_logs.id
-- -----------------------------------------------------------------------------

ALTER TABLE public.call_briefs
    ADD CONSTRAINT fk_call_briefs_call_log_id
    FOREIGN KEY (call_log_id) REFERENCES public.call_logs(id);


-- -----------------------------------------------------------------------------
-- 8. sequence_enrollments
-- -----------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS public.sequence_enrollments (
    id                  bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    contact_id          bigint REFERENCES public.contacts(id),
    sequence_id         text REFERENCES public.sequences(id),
    enrolled_at         timestamptz DEFAULT now(),
    current_step        integer DEFAULT 1,
    current_step_due    timestamptz,
    status              text DEFAULT 'active',  -- 'active','paused','completed','exited'
    exit_reason         text,  -- 'replied_positive','replied_negative','replied_not_now','completed_no_response','manual'
    completed_at        timestamptz,
    paused_at           timestamptz,
    paused_reason       text,
    steps_completed     jsonb DEFAULT '[]',
    notes               text
);

CREATE INDEX IF NOT EXISTS idx_seq_enrollments_contact_id       ON public.sequence_enrollments(contact_id);
CREATE INDEX IF NOT EXISTS idx_seq_enrollments_sequence_id      ON public.sequence_enrollments(sequence_id);
CREATE INDEX IF NOT EXISTS idx_seq_enrollments_status           ON public.sequence_enrollments(status);
CREATE INDEX IF NOT EXISTS idx_seq_enrollments_current_step_due ON public.sequence_enrollments(current_step_due);

ALTER TABLE public.sequence_enrollments ENABLE ROW LEVEL SECURITY;

CREATE POLICY "anon_select_sequence_enrollments" ON public.sequence_enrollments
    FOR SELECT TO anon USING (true);

CREATE POLICY "anon_insert_sequence_enrollments" ON public.sequence_enrollments
    FOR INSERT TO anon WITH CHECK (true);

CREATE POLICY "anon_update_sequence_enrollments" ON public.sequence_enrollments
    FOR UPDATE TO anon USING (true) WITH CHECK (true);


-- -----------------------------------------------------------------------------
-- 9. events (Event Bus)
-- -----------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS public.events (
    id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_type      text NOT NULL,
    contact_id      bigint REFERENCES public.contacts(id),
    firm_id         bigint REFERENCES public.institutional_firms(id),
    actor           text,       -- 'hunter','marshall','system'
    channel         text,       -- 'email','linkedin','phone','system'
    payload         jsonb NOT NULL DEFAULT '{}',
    sequence_id     text,
    sequence_step   integer,
    created_at      timestamptz DEFAULT now(),
    processed_at    timestamptz,
    processed_by    text
);

CREATE INDEX IF NOT EXISTS idx_events_event_type   ON public.events(event_type);
CREATE INDEX IF NOT EXISTS idx_events_contact_id   ON public.events(contact_id);
CREATE INDEX IF NOT EXISTS idx_events_created_at   ON public.events(created_at);
CREATE INDEX IF NOT EXISTS idx_events_processed_at ON public.events(processed_at);

ALTER TABLE public.events ENABLE ROW LEVEL SECURITY;

CREATE POLICY "anon_select_events" ON public.events
    FOR SELECT TO anon USING (true);

CREATE POLICY "anon_insert_events" ON public.events
    FOR INSERT TO anon WITH CHECK (true);


-- -----------------------------------------------------------------------------
-- 10. retail_comm_tracker
-- -----------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS public.retail_comm_tracker (
    id                        bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    period_start              date NOT NULL,
    period_end                date NOT NULL,
    contact_count             integer DEFAULT 0,
    contact_ids               jsonb DEFAULT '[]',
    threshold_warning_sent    boolean DEFAULT false,
    threshold_exceeded        boolean DEFAULT false,
    created_at                timestamptz DEFAULT now()
);

ALTER TABLE public.retail_comm_tracker ENABLE ROW LEVEL SECURITY;

CREATE POLICY "anon_select_retail_comm_tracker" ON public.retail_comm_tracker
    FOR SELECT TO anon USING (true);

CREATE POLICY "anon_insert_retail_comm_tracker" ON public.retail_comm_tracker
    FOR INSERT TO anon WITH CHECK (true);


-- =============================================================================
-- END OF MIGRATION
-- =============================================================================
